// Mock data for the Zero Hunger platform

export const donorDonations = [
  {
    id: "DN-8821",
    name: "Fresh Produce Mix",
    weight: "12kg",
    status: "pending" as const,
    expiresIn: "2 days",
    note: "Awaiting Driver",
    image: "https://images.unsplash.com/photo-1542838132-92c53300491e?w=400&h=300&fit=crop",
    category: "Vegetables/Fruits",
  },
  {
    id: "DN-8756",
    name: "Assorted Bread",
    weight: "8kg",
    status: "accepted" as const,
    expiresIn: "1 day",
    note: "Driver Assigned: Mike Ross",
    image: "https://images.unsplash.com/photo-1509440159596-0249088772ff?w=400&h=300&fit=crop",
    category: "Bakery",
  },
  {
    id: "DN-8612",
    name: "Hot Meals (15 portions)",
    weight: "15 portions",
    status: "delivered" as const,
    expiresIn: "Yesterday",
    note: "Received at: Downtown Shelter",
    image: "https://images.unsplash.com/photo-1547592180-85f173990554?w=400&h=300&fit=crop",
    category: "Cooked Meals",
  },
];

export const deliveries = [
  {
    id: "DEL-001",
    foodType: "FRESH VEGETABLES",
    item: "45kg Assorted Greens",
    icon: "eco",
    iconBg: "bg-emerald-50",
    iconColor: "text-emerald-600",
    status: "accepted" as const,
    donor: "Organic Harvest Farms",
    recipient: "The Community Kitchen",
    steps: ["pending", "accepted", "pending"] as ("done" | "active" | "pending")[],
  },
  {
    id: "DEL-002",
    foodType: "BAKERY PRODUCTS",
    item: "200 Fresh Loaves",
    icon: "bakery_dining",
    iconBg: "bg-orange-50",
    iconColor: "text-orange-600",
    status: "pending" as const,
    donor: "Main Street Bakery",
    recipient: "Hope Shelter Home",
    steps: ["active", "pending", "pending"] as ("done" | "active" | "pending")[],
  },
  {
    id: "DEL-003",
    foodType: "DAIRY PRODUCTS",
    item: "150 Cartons Yogurt",
    icon: "water_drop",
    iconBg: "bg-blue-50",
    iconColor: "text-blue-600",
    status: "delivered" as const,
    donor: "City Supermart",
    recipient: "Youth Empowerment Center",
    steps: ["done", "done", "done"] as ("done" | "active" | "pending")[],
  },
];

export const ngoListings = [
  {
    id: "LISTING-001",
    name: "Fresh Produce Box",
    quantity: "24 kg",
    description: "Mixed seasonal vegetables and fruits from local organic market. Best for soup kitchens.",
    expiresIn: "6h",
    expiryPercent: 75,
    expiryColor: "bg-red-500",
    distance: "0.8 km",
    urgency: "urgent" as const,
    image: "https://images.unsplash.com/photo-1518843875459-f738682238a6?w=600&h=400&fit=crop",
  },
  {
    id: "LISTING-002",
    name: "Assorted Bakery Items",
    quantity: "12 units",
    description: "Whole grain breads, sourdough loaves, and various breakfast pastries. Still warm from morning bake.",
    expiresIn: "18h",
    expiryPercent: 25,
    expiryColor: "bg-emerald-500",
    distance: "2.4 km",
    urgency: "available" as const,
    image: "https://images.unsplash.com/photo-1509440159596-0249088772ff?w=600&h=400&fit=crop",
  },
  {
    id: "LISTING-003",
    name: "Catered Lunch Boxes",
    quantity: "45 boxes",
    description: "Individually packed nutritious lunches from a corporate event. High protein and vegetarian options.",
    expiresIn: "10h",
    expiryPercent: 50,
    expiryColor: "bg-amber-500",
    distance: "1.1 km",
    urgency: "available" as const,
    image: "https://images.unsplash.com/photo-1547592180-85f173990554?w=600&h=400&fit=crop",
  },
];

export const adminTransactions = [
  {
    id: "TXN-001",
    donor: "Green Foods Co.",
    donorInitials: "GF",
    donorColor: "bg-emerald-100 text-emerald-700",
    recipient: "City Shelter Org.",
    itemType: "Bakery Products",
    status: "delivered" as const,
  },
  {
    id: "TXN-002",
    donor: "Metro Supermarket",
    donorInitials: "MS",
    donorColor: "bg-blue-100 text-blue-700",
    recipient: "Helping Hands",
    itemType: "Fresh Produce",
    status: "in-transit" as const,
  },
  {
    id: "TXN-003",
    donor: "Baker's Kitchen",
    donorInitials: "BK",
    donorColor: "bg-emerald-100 text-emerald-700",
    recipient: "Youth Center",
    itemType: "Canned Goods",
    status: "delivered" as const,
  },
  {
    id: "TXN-004",
    donor: "Harvest Market",
    donorInitials: "HM",
    donorColor: "bg-amber-100 text-amber-700",
    recipient: "Community Pantry",
    itemType: "Fresh Produce",
    status: "pending" as const,
  },
];

export const expiryAlerts = [
  {
    id: "ALERT-001",
    item: "Pasteurized Milk (20L)",
    timeLeft: "4h left",
    location: "Hub A, Shelf 4",
    action: "Assign Immediate Pickup",
    actionVariant: "danger" as const,
  },
  {
    id: "ALERT-002",
    item: "Fresh Strawberries (5kg)",
    timeLeft: "6h left",
    location: "Metro Mart Donor",
    action: "Alert Local NGO",
    actionVariant: "outline" as const,
  },
];
